name: CI - Build and Test Sparse Matrix App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint check
      run: |
        pip install flake8
        flake8 api streamlit_app --ignore=E501

    - name: Run quick data sanity test
      run: |
        python -c "import pandas as pd; print('✅ Pandas loaded, all good!')"
